version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    container_name: dillinger-backend-dev
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend/src:/app/packages/backend/src
      - ./packages/shared/src:/app/packages/shared/src
      - /var/run/docker.sock:/var/run/docker.sock
      - game-library:/opt/games
      - json-data:/data
    environment:
      - NODE_ENV=development
      - DATA_PATH=/data
      - GAME_LIBRARY_PATH=/opt/games
      - FRONTEND_URL=http://localhost:3000
    restart: unless-stopped
    depends_on:
      - shared-build

  frontend-dev:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.dev
    container_name: dillinger-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend/app:/app/packages/frontend/app
      - ./packages/frontend/next.config.js:/app/packages/frontend/next.config.js
      - ./packages/frontend/tailwind.config.js:/app/packages/frontend/tailwind.config.js
      - ./packages/frontend/postcss.config.js:/app/packages/frontend/postcss.config.js
      - ./packages/shared/src:/app/packages/shared/src
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    restart: unless-stopped
    depends_on:
      - shared-build

  shared-build:
    build:
      context: .
      dockerfile: ./docker/shared/Dockerfile.build
    container_name: dillinger-shared-build
    volumes:
      - ./packages/shared/src:/app/packages/shared/src
      - shared-dist:/app/packages/shared/dist
    command: pnpm run build

volumes:
  game-library:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/games
      o: bind
  json-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/storage
      o: bind
  shared-dist:
    driver: local