// PM2 ecosystem configuration for running both backend and frontend
module.exports = {
  apps: [
    {
      name: 'dillinger-backend',
      cwd: '/app/packages/backend',
      script: 'node',
      args: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.BACKEND_PORT || '4001',
        DILLINGER_ROOT: process.env.DILLINGER_ROOT || '/data',
        FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:4000',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      error_file: '/dev/null',
      out_file: '/dev/null',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'dillinger-frontend',
      cwd: '/app/packages/frontend',
      script: 'pnpm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || '4000',
        NEXT_PUBLIC_API_URL: process.env.FRONTEND_URL || 'http://localhost:4000',
        BACKEND_URL: `http://localhost:${process.env.BACKEND_PORT || '4001'}`,
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      error_file: '/dev/null',
      out_file: '/dev/null',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
