#!/bin/bash
# Dillinger FS-UAE Amiga Emulator Runner - Entrypoint Wrapper
# Calls base entrypoint first, then sets up FS-UAE environment
set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  FS-UAE Runner - Initializing...${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Set up basic environment variables that base entrypoint would set
UNAME="${UNAME:-gameuser}"
PUID="${PUID:-1000}"
PGID="${PGID:-1000}"

# Export display and audio variables if they exist
export DISPLAY="${DISPLAY:-:0}"
export PULSE_SERVER="${PULSE_SERVER:-unix:/run/user/1000/pulse/native}"
export PULSE_COOKIE="${PULSE_COOKIE:-/home/${UNAME}/.config/pulse/cookie}"

# Set XAUTHORITY if xauth file is mounted
if [ -f "/home/${UNAME}/.Xauthority" ]; then
    export XAUTHORITY="/home/${UNAME}/.Xauthority"
fi

echo -e "${GREEN}Display configured: ${DISPLAY}${NC}"
if [ -n "$XAUTHORITY" ]; then
    echo -e "${GREEN}X11 auth configured: ${XAUTHORITY}${NC}"
fi
echo ""

#######################################################
# FS-UAE-Specific Setup
#######################################################

echo -e "${BLUE}Configuring FS-UAE environment...${NC}"

# Set FS-UAE defaults if not already set
FSUAE_CONFIG_DIR="${FSUAE_CONFIG_DIR:-/config/fs-uae}"
FSUAE_KICKSTARTS_DIR="${FSUAE_KICKSTARTS_DIR:-/bios}"

export FSUAE_CONFIG_DIR
export FSUAE_KICKSTARTS_DIR

echo "  FS-UAE Config Dir: $FSUAE_CONFIG_DIR"
echo "  FS-UAE Kickstarts Dir: $FSUAE_KICKSTARTS_DIR"

# Create FS-UAE configuration directory if it doesn't exist
if [ ! -d "$FSUAE_CONFIG_DIR" ]; then
    echo -e "${BLUE}Creating FS-UAE configuration directory...${NC}"
    mkdir -p "$FSUAE_CONFIG_DIR"
    chown -R "${UNAME:-gameuser}":"${UNAME:-gameuser}" "$FSUAE_CONFIG_DIR"
    echo -e "${GREEN}✓ FS-UAE configuration directory created${NC}"
else
    echo -e "${GREEN}✓ FS-UAE configuration directory exists${NC}"
fi

# Create kickstarts directory if it doesn't exist
if [ ! -d "$FSUAE_KICKSTARTS_DIR" ]; then
    echo -e "${BLUE}Creating FS-UAE kickstarts directory...${NC}"
    mkdir -p "$FSUAE_KICKSTARTS_DIR"
    chown -R "${UNAME:-gameuser}":"${UNAME:-gameuser}" "$FSUAE_KICKSTARTS_DIR"
    echo -e "${GREEN}✓ FS-UAE kickstarts directory created${NC}"
else
    echo -e "${GREEN}✓ FS-UAE kickstarts directory exists${NC}"
    # Try to fix permissions, but don't fail if read-only mount
    chown -R "${UNAME:-gameuser}":"${UNAME:-gameuser}" "$FSUAE_KICKSTARTS_DIR" 2>/dev/null || echo -e "${YELLOW}  ⚠ Could not chown kickstarts directory (likely read-only mount)${NC}"
fi

# Verify FS-UAE emulator availability
echo -e "${BLUE}Verifying FS-UAE emulator...${NC}"
if command -v fs-uae >/dev/null 2>&1; then
    FS_UAE_VERSION=$(fs-uae --version 2>&1 | head -n 1 || echo "Unknown")
    echo -e "${GREEN}  ✓ fs-uae available: $FS_UAE_VERSION${NC}"
else
    echo -e "${YELLOW}  ⚠ fs-uae not found${NC}"
fi

# Configure FS-UAE settings based on environment variables
# These can be overridden by the user via environment variables

# Video settings
FSUAE_FULLSCREEN="${FSUAE_FULLSCREEN:-0}"
FSUAE_VSYNC="${FSUAE_VSYNC:-1}"
FSUAE_VIDEO_SYNC="${FSUAE_VIDEO_SYNC:-1}"

# Audio settings
FSUAE_AUDIO_FREQUENCY="${FSUAE_AUDIO_FREQUENCY:-44100}"
FSUAE_AUDIO_BUFFER_SIZE="${FSUAE_AUDIO_BUFFER_SIZE:-2048}"

# Performance settings
FSUAE_ACCURACY="${FSUAE_ACCURACY:-1}"  # 0=Fast, 1=Compatible (default)

# Amiga Model and Kickstart
FSUAE_AMIGA_MODEL="${FSUAE_AMIGA_MODEL:-A500}"
FSUAE_KICKSTART="${FSUAE_KICKSTART:-}"

echo -e "${BLUE}FS-UAE Configuration:${NC}"
echo "  Fullscreen: $FSUAE_FULLSCREEN"
echo "  VSync: $FSUAE_VSYNC"
echo "  Video Sync: $FSUAE_VIDEO_SYNC"
echo "  Audio Frequency: $FSUAE_AUDIO_FREQUENCY Hz"
echo "  Accuracy: $FSUAE_ACCURACY"
echo "  Amiga Model: $FSUAE_AMIGA_MODEL"
if [ -n "$FSUAE_KICKSTART" ]; then
    echo "  Kickstart Override: $FSUAE_KICKSTART"
fi

# Generate FS-UAE Configuration File
# We write to Default.fs-uae in the standard location so it's picked up automatically
FSUAE_BASE_DIR="/home/${UNAME:-gameuser}/FS-UAE"
FSUAE_CONFIGS_DIR="$FSUAE_BASE_DIR/Configurations"
mkdir -p "$FSUAE_CONFIGS_DIR"

CONFIG_FILE="$FSUAE_CONFIGS_DIR/Default.fs-uae"
echo -e "${BLUE}Generating configuration file at $CONFIG_FILE...${NC}"

cat > "$CONFIG_FILE" <<EOF
# Generated by Dillinger FS-UAE Runner
[config]
amiga_model = $FSUAE_AMIGA_MODEL
fullscreen = $FSUAE_FULLSCREEN
video_sync = $FSUAE_VIDEO_SYNC
accuracy = $FSUAE_ACCURACY
kickstarts_dir = $FSUAE_KICKSTARTS_DIR
# Force PulseAudio for OpenAL
bsdsocket_library = 1
EOF

# Add Kickstart override if specified
if [ -n "$FSUAE_KICKSTART" ]; then
    # Check if it's a full path or relative to kickstarts dir
    if [ -f "$FSUAE_KICKSTART" ]; then
        echo "kickstart_file = $FSUAE_KICKSTART" >> "$CONFIG_FILE"
    elif [ -f "$FSUAE_KICKSTARTS_DIR/$FSUAE_KICKSTART" ]; then
        echo "kickstart_file = $FSUAE_KICKSTARTS_DIR/$FSUAE_KICKSTART" >> "$CONFIG_FILE"
    else
        echo -e "${YELLOW}  ⚠ Kickstart file '$FSUAE_KICKSTART' not found, ignoring override${NC}"
    fi
fi

# Ensure config file and directory are owned by gameuser
chown -R "${UNAME:-gameuser}":"${UNAME:-gameuser}" "$FSUAE_BASE_DIR"

# Configure OpenAL for gameuser
echo "drivers = pulse" > "/home/${UNAME:-gameuser}/.alsoftrc"
chown "${UNAME:-gameuser}":"${UNAME:-gameuser}" "/home/${UNAME:-gameuser}/.alsoftrc"

# Check for kickstart ROMs
echo -e "${BLUE}Checking for Kickstart ROMs...${NC}"
KICKSTART_COUNT=$(find "$FSUAE_KICKSTARTS_DIR" -type f \( -name "*.rom" -o -name "*.ROM" -o -name "*.bin" -o -name "*.BIN" \) 2>/dev/null | wc -l)
if [ "$KICKSTART_COUNT" -gt 0 ]; then
    echo -e "${GREEN}  ✓ Found $KICKSTART_COUNT kickstart ROM(s)${NC}"
else
    echo -e "${RED}  ✗ No kickstart ROMs found in $FSUAE_KICKSTARTS_DIR${NC}"
    echo -e "${RED}    Kickstart ROMs are required for Amiga emulation${NC}"
    echo -e "${RED}    Place your kickstart ROMs (e.g., kick*.rom) in the BIOS directory${NC}"
    echo -e "${RED}    Upload them via the Platforms page in Dillinger${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  FS-UAE Runner Ready${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Execute command as game user if provided
if [ "$#" -gt 0 ]; then
    echo -e "${BLUE}Executing command: $*${NC}"
    echo ""
    exec gosu "${UNAME:-gameuser}" "$@"
else
    echo -e "${BLUE}No command provided, starting shell...${NC}"
    echo ""
    exec gosu "${UNAME:-gameuser}" /bin/bash
fi
