services:
  ####################
  builder:
    image: ${NAME_BUILDER}:${VERSION_BUILDER}
    build:
      context: ../
      dockerfile: ./images/builder/Dockerfile
      args:
        BASE_IMAGE: ${NAME_BASE}:${VERSION_BASE}
    stdin_open: true 
    tty: true
    network_mode: host
    volumes:
      - dillinger:/home

volumes: 
  dillinger: