# The master dillinger config file. The beginning of all things...

# The port the server will listen on
port = 3060

# The root directory of all files handled by dillinger
root_dir = "./dev_root_dir"

# Define the supported platform names
# These are the directory names that dillinger will look for during an audit
platforms = [
    {name = "linux", description = "linux on linux"},
    {name = "wine", description = "windows on linux"},
    {name = "arcade", description = "mame based arcade roms"}
]
