include:
  - base.yml
services:
  ####################
  wine-ge-custom:
    image: ${DOCKER_PREFIX}/${NAME_WINE_GE_CUSTOM}:${VERSION_WINE_GE_CUSTOM}
    build:
      context: ../
      dockerfile: ./images/wine-ge-custom/Dockerfile
    depends_on:
      - base
    stdin_open: true 
    tty: true
    network_mode: host
    volumes:
      - dillinger:/dillinger